spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DB}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

mercadopago.access.token=${MP_ACCESS_TOKEN}
mercadopago.notification.url=http://${EC2_PUBLIC_IP}/api/order/webhook
app.frontend.url=http://${EC2_PUBLIC_IP}
jwt.secret.key=${JWT_SECRET_KEY}

cloud.aws.credential.access-key=${AWS_ACCESS_KEY}
cloud.aws.credential.secret-key=${AWS_SECRET_KEY}

email.admin=${EMAIL_ADMIN}
password.admin=${PASSWORD_ADMIN}
    