-- Baseline schema for the e-commerce database.
--
-- Generated by letting Hibernate create the schema from the JPA entities
-- (ddl-auto=create) against PostgreSQL 16 and dumping the result, so it matches
-- what spring.jpa.hibernate.ddl-auto=validate expects on startup byte for byte.
--
-- Databases that predate Flyway (created by the old ddl-auto=update) are stamped
-- at this version by spring.flyway.baseline-on-migrate=true rather than having
-- this script replayed against them. Fresh databases get it applied normally.
--
-- Do not edit this file. Schema changes go in a new V2__*.sql.

-- Name: cart; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.cart (
    created_date timestamp(6) with time zone,
    id bigint NOT NULL,
    id_user bigint,
    status character varying(255),
    CONSTRAINT cart_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'CHECKOUT'::character varying])::text[])))
);

-- Name: cart_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: cart_item; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.cart_item (
    quantity integer NOT NULL,
    cart_id bigint,
    id bigint NOT NULL,
    product_id bigint
);

-- Name: cart_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.cart_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: category; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.category (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    s3key character varying(255) NOT NULL,
    url character varying(255) NOT NULL
);

-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: collection; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.collection (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    s3key character varying(255) NOT NULL,
    url character varying(255) NOT NULL
);

-- Name: collection_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.collection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: ordem_item; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.ordem_item (
    quantity integer NOT NULL,
    unit_price numeric(38,2) NOT NULL,
    id bigint NOT NULL,
    order_id bigint,
    product_id bigint NOT NULL,
    description character varying(255) NOT NULL,
    product_name character varying(255) NOT NULL,
    url character varying(255) NOT NULL
);

-- Name: ordem_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.ordem_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ordem_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: orders; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.orders (
    shipping_cost numeric(38,2),
    total numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    paid_at timestamp(6) without time zone,
    user_id bigint,
    mercado_pago_payment_id character varying(255),
    mercado_pago_preference_id character varying(255),
    status character varying(255),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying])::text[])))
);

-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: product; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.product (
    price_discount numeric(38,2),
    price_original numeric(38,2) NOT NULL,
    quantity integer NOT NULL,
    id bigint NOT NULL,
    main_image_id bigint,
    description character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);

-- Name: product_category; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.product_category (
    category_id bigint NOT NULL,
    product_id bigint NOT NULL
);

-- Name: product_collection; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.product_collection (
    collection_id bigint NOT NULL,
    product_id bigint NOT NULL
);

-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: product_image; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.product_image (
    is_main boolean NOT NULL,
    id bigint NOT NULL,
    product_id bigint,
    s3_key character varying(255) NOT NULL,
    url character varying(255) NOT NULL
);

-- Name: product_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.product_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: user_address; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.user_address (
    id bigint NOT NULL,
    bairro character varying(255),
    cep character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    number character varying(255) NOT NULL,
    phone character varying(255),
    street character varying(255) NOT NULL
);

-- Name: user_address_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.user_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: users; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.users (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_adress_id bigint,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    user_role character varying(255) NOT NULL,
    CONSTRAINT users_user_role_check CHECK (((user_role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);

-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: cart_item cart_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT cart_item_pkey PRIMARY KEY (id);

-- Name: cart cart_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_pkey PRIMARY KEY (id);

-- Name: category category_name_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_name_key UNIQUE (name);

-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);

-- Name: collection collection_name_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.collection
    ADD CONSTRAINT collection_name_key UNIQUE (name);

-- Name: collection collection_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.collection
    ADD CONSTRAINT collection_pkey PRIMARY KEY (id);

-- Name: ordem_item ordem_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.ordem_item
    ADD CONSTRAINT ordem_item_pkey PRIMARY KEY (id);

-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

-- Name: product_category product_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT product_category_pkey PRIMARY KEY (category_id, product_id);

-- Name: product_collection product_collection_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.product_collection
    ADD CONSTRAINT product_collection_pkey PRIMARY KEY (collection_id, product_id);

-- Name: product_image product_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.product_image
    ADD CONSTRAINT product_image_pkey PRIMARY KEY (id);

-- Name: product product_main_image_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_main_image_id_key UNIQUE (main_image_id);

-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);

-- Name: user_address user_address_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_address
    ADD CONSTRAINT user_address_pkey PRIMARY KEY (id);

-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- Name: users users_user_adress_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_adress_id_key UNIQUE (user_adress_id);

-- Name: cart_item fk1uobyhgl1wvgt1jpccia8xxs3; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT fk1uobyhgl1wvgt1jpccia8xxs3 FOREIGN KEY (cart_id) REFERENCES public.cart(id);

-- Name: product_category fk2k3smhbruedlcrvu6clued06x; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT fk2k3smhbruedlcrvu6clued06x FOREIGN KEY (product_id) REFERENCES public.product(id);

-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);

-- Name: product_image fk6oo0cvcdtb6qmwsga468uuukk; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.product_image
    ADD CONSTRAINT fk6oo0cvcdtb6qmwsga468uuukk FOREIGN KEY (product_id) REFERENCES public.product(id);

-- Name: product_collection fkc5yg30bbi3rip4hns0rm3vq21; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.product_collection
    ADD CONSTRAINT fkc5yg30bbi3rip4hns0rm3vq21 FOREIGN KEY (collection_id) REFERENCES public.collection(id);

-- Name: cart_item fkjcyd5wv4igqnw413rgxbfu4nv; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT fkjcyd5wv4igqnw413rgxbfu4nv FOREIGN KEY (product_id) REFERENCES public.product(id);

-- Name: cart fkk0lcwd6e5q8ldue7je6efhdot; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT fkk0lcwd6e5q8ldue7je6efhdot FOREIGN KEY (id_user) REFERENCES public.users(id);

-- Name: product fkk1voou9lux0e04e9owcu4txcx; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fkk1voou9lux0e04e9owcu4txcx FOREIGN KEY (main_image_id) REFERENCES public.product_image(id);

-- Name: product_category fkkud35ls1d40wpjb5htpp14q4e; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT fkkud35ls1d40wpjb5htpp14q4e FOREIGN KEY (category_id) REFERENCES public.category(id);

-- Name: users fkl15mqqv6glxnt2veibsqtxwcj; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkl15mqqv6glxnt2veibsqtxwcj FOREIGN KEY (user_adress_id) REFERENCES public.user_address(id);

-- Name: ordem_item fkr10t612jq75nqch904ietmwsf; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.ordem_item
    ADD CONSTRAINT fkr10t612jq75nqch904ietmwsf FOREIGN KEY (order_id) REFERENCES public.orders(id);

-- Name: product_collection fksm53vng5s8bqgt2vl7yx0h0ws; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.product_collection
    ADD CONSTRAINT fksm53vng5s8bqgt2vl7yx0h0ws FOREIGN KEY (product_id) REFERENCES public.product(id);
